// This file is generated by npm run build:icons

export type IconName =
	| 'avatar'
	| 'check'
	| 'clipboard-copy'
	| 'copy'
	| 'cross-1'
	| 'dashboard'
	| 'exit'
	| 'eye-closed'
	| 'eye-open'
	| 'gear'
	| 'moon'
	| 'sun'
	| 'update';
